#!/data/data/com.termux/files/usr/bin/bash

function main() {
  if [[ $1 = "" ]];then
    echo "No argument"
    exit 0
  fi
  files=($(find $1 -type f -iregex ".*\.\(png\|jpg\|jpeg\)"))
  filecount=${#files[@]}
  if [ $filecount -eq 0 ]; then
    echo "No files in the folder $1"
    exit 1
  fi
  filepath="${files[$(($RANDOM % $filecount))]}"
  termux-wallpaper -f "$filepath"
  exit 0
}

main "$@"
