#!/data/data/com.termux/files/usr/bin/bash
path=$1
termux-notification -t "Wallpaper randomizer" -c "Tap to change wallpaper" --action "change-wallpaper \"${path}\" && wallpaper-notification \"${path}\""
